webtalk_init -webtalk_dir E:/Dev/dev-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.sim/sim_1/behav/xsim/xsim.dir/tb_counter_top_debounce_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 14 00:13:37 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dac96330-f8bf-432b-8864-f68d5d5b2425" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be4ab4ccd7de48d4b6693104766a4610" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11859231 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "161.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15604_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1898404853 -regid "" -xml E:/Dev/dev-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.sim/sim_1/behav/xsim/xsim.dir/tb_counter_top_debounce_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Dev/dev-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.sim/sim_1/behav/xsim/xsim.dir/tb_counter_top_debounce_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Dev/dev-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.sim/sim_1/behav/xsim/xsim.dir/tb_counter_top_debounce_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
