@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 26 03:29:15 +0900 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_asd_4_behav -key {Behavioral:sim_1:Functional:tb_asd_4} -tclbatch tb_asd_4.tcl -view E:/Dev/dev-git/digital-system-design-verilog/design_practice/3week/3week_lab/tb_rca_16_func_synth.wcfg -log simulate.log"
call xsim  tb_asd_4_behav -key {Behavioral:sim_1:Functional:tb_asd_4} -tclbatch tb_asd_4.tcl -view E:/Dev/dev-git/digital-system-design-verilog/design_practice/3week/3week_lab/tb_rca_16_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
