# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Dev/sync-git/digital-system-design-verilog/design_practice/10-week/10-week-hw_1/10-week-hw_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
